import Head from "next/head";
import ProfileCard from "../components/ProfileCard";
import { useEffect, useState } from "react";
import axios from "axios";
import { Advocates } from "../types/advocates";
import { useRouter } from "next/router";

export default function Home() {
  const [advocates, setAdvocates] = useState<any>({}); // object coming from the API
  const [currentUser, setCurrentUser] = useState<string | string[] | undefined>(undefined);
  const router = useRouter();

  useEffect(() => {
    setCurrentUser(router?.query?.username);
  }, [router?.query?.username]);

  useEffect((): void => {
    const getInfo = async (): Promise<any> => {
      try {
        const response: any = await axios.get("https://cados.up.railway.app/advocates/");
        setAdvocates(response.data);
        console.log(response.data);
      } catch (err: unknown) {
        console.log(err);
      }
    };
    getInfo();
  }, []);

  const handleChangeUser = (e: any): void => {
    setCurrentUser((e.target as HTMLInputElement).value);
  };

  return (
    <div>
      <Head>
        <title>My NextJS App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full mx-auto'>
        <div className='w-full flex justify-center items-center my-8'>
          <div className='mt-12'>
            <input
              type='search'
              value={currentUser ?? ''}
              onChange={handleChangeUser}
              placeholder='Search name...'
              className='md:w-96 w-full py-2 px-3 text-lg rounded-md shadow-md outline-none border-2 border-slate-400 focus:border-blue-500'
            />
          </div>
        </div>

        <div className='flex flex-wrap justify-center'>
          {advocates?.advocates?.map((advocate: Advocates, idx: number) => {
            return <ProfileCard key={idx} advocate={advocate} />;
          })}
        </div>
      </div>
    </div>
  );
}
