import Head from "next/head";
import ProfileCard from "../components/ProfileCard";
import { useEffect, useRef, useState } from "react";
import { Advocates } from "../types/advocates";
import Pagination from "../components/Pagination";
import { getAdvocates, getAdvocate } from "../service/advocates.api";
import useCacheResponse from "../hooks/useCacheResponse";
import Spinner from "../components/Spinner";

export default function Home() {
  const [advocates, setAdvocates] = useState<any>({}); // object coming from the API
  const [currentUser, setCurrentUser] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [getFromCache, saveToCache] = useCacheResponse();
  const currentPage = useRef<number>(0);

  const getAndSaveAdvocates = async (pageNo: number) => {
    try {
      setLoading(true);
      let response: any = {};
      if (!getFromCache(pageNo)) {
        response = await getAdvocates(pageNo);
        saveToCache(pageNo, response);
      } else {
        response = getFromCache(pageNo);
      }
      setAdvocates(response);
      currentPage.current = pageNo;
    } catch (err: unknown) {
      console.log(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect((): void => {
    const getInfo = async (): Promise<any> => {
      return await getAndSaveAdvocates(1);
    };
    getInfo();
  }, []);

  const handlePageChange = async (pageNo: number): Promise<any> => {
    return await getAndSaveAdvocates(pageNo);
  };

  const handleChangeUser = (e: any): void => {
    return setCurrentUser((e.target as HTMLInputElement).value);
  };

  const handleKeyUp = async (e: any): Promise<any> => {
    if (e.key === "Enter" && !!currentUser) {
      try {
        const response: any = await getAdvocate(currentUser);
        setAdvocates({ advocates: [response?.advocate] });
      } catch (err: unknown) {
        setAdvocates({ advocates: [] });
      }
    } else if (e.key === "Enter" && !currentUser) {
      await getAndSaveAdvocates(currentPage.current);
    }
  };

  return (
    <div>
      <Head>
        <title>My NextJS App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {loading && (
        <div className=' h-screen flex justify-center items-center '>
          <Spinner />
        </div>
      )}

      <div className='w-full mx-auto sm:min-w-min'>
        <div className='w-full flex justify-center items-center my-8'>
          <div className='mt-12'>
            <input
              type='search'
              value={currentUser ?? ""}
              onChange={handleChangeUser}
              onKeyUp={handleKeyUp}
              placeholder='Search name...'
              className='md:w-96 w-full py-2 px-3 text-lg rounded-md shadow-md outline-none border-2 border-slate-400 focus:border-blue-500 bg-gray-800'
            />
          </div>
        </div>

        {!loading && !advocates?.advocates?.length && (
          <p className='text-white text-center text-lg font-semibold'>No Advocated Found</p>
        )}

        {!!advocates?.advocates?.length && (
          <>
            <div className='flex flex-wrap justify-center sm:p-5'>
              {advocates?.advocates?.map((advocate: Advocates, idx: number) => {
                return <ProfileCard key={idx} advocate={advocate} />;
              })}
            </div>
            {!currentUser && <div className='flex justify-center'>
              <Pagination {...advocates?.pagination} handlePageChange={handlePageChange} />
            </div>}
          </>
        )}
      </div>
    </div>
  );
}
